### ISSUE TITLE
Does this code still work?

### ISSUE THREAD

**Issue by kpdillon** [cmichi/twitterwall#4]
Hi, I followed the instructions and installed on a new Ubuntu Server.  When I type node server.js it doesn't seem to start anything up that listens on port 3000.  How can I debug?

**Comment by cmichi** [comment]
Hi there! The code should still work (http://twitterwall.creal.de/ is a running instance). The code is a bit dated though, so there might be the need to do some adjustments. 

Can you post the output you get when you try to start it? Are there any errors? What version of node.js do you use?

**Comment by kpdillon** [comment]
Hi!  Thank you for the quick reply.  I was able to get it started by typing nodejs server.js instead of node server.js.  However, now it is just stick on loading.... Is there a log I can check for that?

**Comment by kpdillon** [comment]
I am running node 4.4.2.  What version is running on the demo server?  Could that be the issue?

**Comment by cmichi** [comment]
The demo is running on v7.2.1, but it should also work with 4.4.2. The log output should be shown on the terminal, right after you type `node server.js`, is there any output at all after you execute the command?

**Comment by kpdillon** [comment]
ok, I tried upgrading to v7.4.0 and it is still stuck on loading when I start it.  This is what the command line says.  I am running this on ubuntu.  Would it help if I gave you remote access to look at it?

root@ubuntu:/home/twitterwall/twitterwall# node server.js
Option close timeout is not valid. Please refer to the README.
Listening on port 3000

**Comment by cmichi** [comment]
Do you have valid twitter auth credentials in the `config.js` (https://github.com/cmichi/twitterwall#installation)? That would be the most probable explanation for the website showing up, but only displaying the loading circle and no tweets.

Also could you please try to remove the folder `node_modules` and do a fresh `npm install`? Just to be sure that the node upgrade and the packages are consistent.

**Comment by cmichi** [comment]
I close the issue because of inactivity.
